---
- hosts: 172.31.38.79
  become: true
  tasks:
    - name: stop project2 docker container
      command: docker stop project2
      ignore_errors: yes
      
    - name: remove stoped container
      command: docker rm project2
      ignore_errors: yes
      
    - name: remove docker image
      command: docker rmi manju1710/devopsproject2:latest
      ignore_errors: yes
      
    - name: create container using manju1710/devopsproject2:latest
      command: docker run -d --name project2 -p 3000:3000 manju1710/devopsproject2:latest
